mysql:
  host: hostname
  port: 3306
  database: database
  username: username
  password: password 
crateLocation:
  world: world
  x: 27
  y: 63
  z: -14
scoreboards:
  normal:
    title: "&d&lCOLONY&F&LMC"
    lines:
      - '&7Skyblock Dimension'
      - ' '
      - '&5┏━ &d%player_name%'
      - '&5┃ &7Rank » &d%vault_rank%'
      - '&5┃ &7Balance » &d%player_balance_formatted%'
      - '&5┃ &7Votes » &d%player_votes% votes'
      - '&5┣━ &d&lIsland'
      - '&5┃ &7Owner » &d%island_owner%'
      - '&5┃ &7Level » &d%island_level%'
      - '&5┃ &7Members » &d%island_members%'
      - '&5┗━ &dOnline: %server_online%'
      - ' '
      - '&d&nstore.colonymc.net'
    updating_lines:
      - 3
      - 4
      - 5
      - 7
      - 8
      - 9
      - 10
  starting:
    title: "&dCreate a guild"
    lines:
      - ' '
      - '&fWelcome to &5&lColonyMC&f!'
      - '&fTo start your journey you'
      - '&fmust create or join a guild!'
      - ' '
      - '&fType &d/guild create <name>'
      - '&for &d/guild join <name>'
      - 'to create/join a new guild!'
      - ' '
      - '&5» &fIP: &dplay.colonymc.net'
    updating_lines: []
  war:
    title: "&5&lGuild War"
    lines:
      - ' '
      - '&fYour Enemy:'
      - ' &d- %war_enemy%'
      - ' '
      - '&fWar Type: &d%war_type%'
      - '&fTime left: &d%war_time_left%'
      - ' '
      - '&fEnemies left: &d%war_enemies_left%'
      - '&fTeam members: &d%war_team_left%'
      - ' '
      - '&5» &fIP: &dplay.colonymc.net'
    updating_lines:
      - 2
      - 4
      - 5
      - 7
      - 8
  war_finished:
    title: "&5&lGuild War"
    lines:
      - ' '
      - '&fYour Enemy:'
      - ' &d- %war_enemy%'
      - ' '
      - '&fWar Type: &d%war_type%'
      - '&fTime left: &d%war_time_left%'
      - ' '
      - '&fWinner:'
      - ' &d- %war_winner%'
      - ' '
      - '&fEnemies left: &d%war_enemies_left%'
      - '&fTeam members: &d%war_team_left%'
      - ' '
      - '&5» &fIP: &dplay.colonymc.net'
    updating_lines:
      - 2
      - 4
      - 5
      - 8
      - 10
      - 11